### ISSUE TITLE
injectJavascript not working in ios

### ISSUE THREAD

**Issue by szfdiwang** [birdofpreyru/react-native-webview#2]
Thx for this solves the issue of executing twice on Android, I found that injectJavaScript has no response on iOS. Can you help us look at this issue again? 
injectJavascript not working in ios

**Comment by szfdiwang** [comment]
I installed the 13.10.7 package and found that it can be executed on iOS, but it still executes twice on Android

**Comment by szfdiwang** [comment]
oh no twice in ios !!!!

**Comment by birdofpreyru** [comment]
Hey @szfdiwang , I haven't seen your message before &mdash; it turns out by default I wasn't subscribed to watch all activity in the forked repo. Do you still experience the issue? In my projects I use `injectJavaScript` on both Android and iOS, and haven't seen any issues with it recently.
